name: Feature request
description: Propose a new feature to add in Smart AutoClicker
labels: ["enhancement"]
body:
  - type: textarea
    id: feature-description
    attributes:
      label: Describe what is the new feature and how it should behave. You can add screenshot or sketches to illustrate it.
      placeholder: "Ex: I would like to have a new type of actions that turns off the devices when executed."
    validations:
      required: true

  - type: input
    id: feature-usage
    attributes:
      label: |
        Describe the usage for this feature. Smart AutoClicker cannot include every feature request, only the ones that
        have a real use case for the most people that uses the app. Please be generic and avoid referencing specific
        app use cases (or as an example for a more general type of usage).
      placeholder: "Ex: Xiaomi phones can explode if they are turned on for more that 10 hours, we need a way to avoid dying "
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Is it a duplicate?
      options:
        - label: I have checked if this feature wasn't already requested
          required: true